"use server";

import { prisma } from "@/lib/config/db";
import { revalidatePath } from "next/cache";
import { stackServerApp } from "@/lib/config/stack";

export async function setQuotePrice(formData: FormData) {
    const id = formData.get("estimateId") as string;
    const projectId = formData.get("projectId") as string;
    let newPrice = parseFloat(formData.get("newPrice") as string);
    const contextCurrency = formData.get("contextCurrency") as string;
    const activeRateStr = formData.get("activeRate") as string;
    const activeRate = activeRateStr ? parseFloat(activeRateStr) : 15000;

    if (!id || isNaN(newPrice)) return { error: "Invalid data" };

    try {
        const estimate = await prisma.estimate.findUnique({
            where: { id },
            include: { service: true }
        });

        if (!estimate) return { error: "Quote not found" };

        // Apply Currency Conversion from Context Currency to Base Currency
        if (contextCurrency && activeRate && estimate.service && contextCurrency !== estimate.service.currency) {
            if (contextCurrency === 'USD' && estimate.service.currency === 'IDR') {
                newPrice = newPrice * activeRate;
            } else if (contextCurrency === 'IDR' && estimate.service.currency === 'USD') {
                newPrice = newPrice / activeRate;
            }
        }
        await prisma.estimate.update({
            where: { id },
            data: {
                totalCost: newPrice,
                status: "pending_payment"
            }
        });

        if (projectId) {
            await prisma.project.update({
                where: { id: projectId },
                data: {
                    status: "pending_payment",
                    totalAmount: newPrice
                }
            });
        }
        revalidatePath("/admin/finance/quotes");
        return { success: true };
    } catch (error) {
        console.error("Error setting quote price:", error);
        return { error: "Failed to update price" };
    }
}

export async function createManualQuote(formData: FormData) {
    const serviceId = formData.get("serviceId") as string;
    const userId = formData.get("userId") as string;
    const clientName = formData.get("clientName") as string;
    const clientEmail = (formData.get("clientEmail") as string) || "";
    let amount = parseFloat(formData.get("amount") as string);
    const contextCurrency = formData.get("contextCurrency") as string;
    const activeRateStr = formData.get("activeRate") as string;
    const activeRate = activeRateStr ? parseFloat(activeRateStr) : 15000;

    if (!serviceId || !userId || isNaN(amount)) return { error: "Missing required fields" };

    const service = await prisma.service.findUnique({ where: { id: serviceId } });
    if (!service) return { error: "Service not found" };

    try {
        let finalClientName = clientName;

        // Auto-fetch name from Stack Auth if not provided and not offline
        if (!finalClientName && userId !== 'OFFLINE') {
            try {
                // ⚡ Bolt Optimization: Use stackServerApp.getUser() instead of listUsers() array lookup
                // 🎯 Why: Avoids O(N) network payload and memory overhead when fetching a single user.
                // 📊 Impact: O(1) performance lookup and reduced API latency.
                const user = await stackServerApp.getUser(userId);
                const fetchedName = user?.displayName || user?.primaryEmail || null;
                if (fetchedName) finalClientName = fetchedName;
            } catch (e) {
                console.error("Failed to fetch user profile from Stack Auth:", e);
            }
        }

        // Apply Currency Conversion from Context Currency to Base Currency
        if (contextCurrency && activeRate && contextCurrency !== service.currency) {
            if (contextCurrency === 'USD' && service.currency === 'IDR') {
                amount = amount * activeRate;
            } else if (contextCurrency === 'IDR' && service.currency === 'USD') {
                amount = amount / activeRate;
            }
        }

        // Create estimate first
        const estimate = await prisma.estimate.create({
            data: {
                prompt: `Manual Quote for ${clientName}${clientEmail ? ` (${clientEmail})` : ''}`,
                title: `${service.title} Quote`,
                summary: clientEmail
                    ? `Custom quote for ${clientName || 'Client'} (${clientEmail})`
                    : `Custom quote generated by admin for ${clientName || 'Client'}`,
                screens: [],
                apis: [],
                totalHours: 0,
                totalCost: amount,
                complexity: "medium",
                status: "pending_offer",
                serviceId: service.id,
            }
        });

        // Create project linked to estimate
        await prisma.project.create({
            data: {
                userId: userId, // Can be a Stack Auth ID or 'OFFLINE'
                title: service.title,
                clientName: finalClientName || (userId === 'OFFLINE' ? "Offline Client" : "Client"),
                status: "pending_offer",
                serviceId: service.id,
                totalAmount: amount,
                estimateId: estimate.id
            }
        });

        revalidatePath("/admin/finance/quotes");
        return { success: true };
    } catch (error) {
        console.error("Error creating manual quote:", error);
        return { error: "Failed to create quote" };
    }
}

/**
 * Hapus estimate (quote) beserta project terkait.
 * Jika userId diberikan, hanya estimate milik user tersebut yang bisa dihapus (untuk client).
 * Jika userId kosong, dianggap request dari admin (unrestricted).
 */
export async function deleteQuote(estimateId: string, userId?: string) {
    if (!estimateId) return { error: "Missing estimate ID" };

    try {
        // Cari estimate beserta project terkait
        const estimate = await prisma.estimate.findUnique({
            where: { id: estimateId },
            include: { project: true },
        });

        if (!estimate) return { error: "Quote not found" };

        // Jika userId diberikan, pastikan estimate ini milik user tersebut
        if (userId && estimate.project?.userId !== userId) {
            return { error: "Unauthorized: you can only delete your own quotes" };
        }

        // Hapus project terkait terlebih dahulu (FK constraint)
        if (estimate.project) {
            await prisma.project.delete({
                where: { id: estimate.project.id },
            });
        }

        // Hapus estimate
        await prisma.estimate.delete({
            where: { id: estimateId },
        });

        revalidatePath("/admin/finance/quotes");
        revalidatePath("/dashboard/quotes");
        return { success: true };
    } catch (error) {
        console.error("Error deleting quote:", error);
        return { error: "Failed to delete quote" };
    }
}
