/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SquadIndexRouteImport } from './routes/squad.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AffiliateIndexRouteImport } from './routes/affiliate.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ViewDesignSlugRouteImport } from './routes/view-design.$slug'
import { Route as SquadProfileRouteImport } from './routes/squad.profile'
import { Route as SquadOnboardingRouteImport } from './routes/squad.onboarding'
import { Route as SquadMissionsRouteImport } from './routes/squad.missions'
import { Route as SquadActiveRouteImport } from './routes/squad.active'
import { Route as HandlerSplatRouteImport } from './routes/handler.$'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardMyProductsRouteImport } from './routes/dashboard.my-products'
import { Route as AffiliateJoinRouteImport } from './routes/affiliate.join'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminPmIndexRouteImport } from './routes/admin.pm.index'
import { Route as AdminSystemCurrencyRouteImport } from './routes/admin.system.currency'
import { Route as AdminPmServicesRouteImport } from './routes/admin.pm.services'
import { Route as AdminPmProjectsRouteImport } from './routes/admin.pm.projects'
import { Route as AdminPmServicesNewRouteImport } from './routes/admin.pm.services.new'
import { Route as AdminPmProjectsIdRouteImport } from './routes/admin.pm.projects.$id'
import { Route as AdminPmServicesIdEditRouteImport } from './routes/admin.pm.services.$id.edit'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const SquadIndexRoute = SquadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SquadRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AffiliateIndexRoute = AffiliateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliateRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ViewDesignSlugRoute = ViewDesignSlugRouteImport.update({
  id: '/view-design/$slug',
  path: '/view-design/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadProfileRoute = SquadProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SquadRoute,
} as any)
const SquadOnboardingRoute = SquadOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SquadRoute,
} as any)
const SquadMissionsRoute = SquadMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => SquadRoute,
} as any)
const SquadActiveRoute = SquadActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => SquadRoute,
} as any)
const HandlerSplatRoute = HandlerSplatRouteImport.update({
  id: '/handler/$',
  path: '/handler/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyProductsRoute = DashboardMyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => DashboardRoute,
} as any)
const AffiliateJoinRoute = AffiliateJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AffiliateRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmIndexRoute = AdminPmIndexRouteImport.update({
  id: '/pm/',
  path: '/pm/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemCurrencyRoute = AdminSystemCurrencyRouteImport.update({
  id: '/system/currency',
  path: '/system/currency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmServicesRoute = AdminPmServicesRouteImport.update({
  id: '/pm/services',
  path: '/pm/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmProjectsRoute = AdminPmProjectsRouteImport.update({
  id: '/pm/projects',
  path: '/pm/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmServicesNewRoute = AdminPmServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPmServicesRoute,
} as any)
const AdminPmProjectsIdRoute = AdminPmProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPmProjectsRoute,
} as any)
const AdminPmServicesIdEditRoute = AdminPmServicesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPmServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/squad': typeof SquadRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/affiliate/join': typeof AffiliateJoinRoute
  '/dashboard/my-products': typeof DashboardMyProductsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/handler/$': typeof HandlerSplatRoute
  '/squad/active': typeof SquadActiveRoute
  '/squad/missions': typeof SquadMissionsRoute
  '/squad/onboarding': typeof SquadOnboardingRoute
  '/squad/profile': typeof SquadProfileRoute
  '/view-design/$slug': typeof ViewDesignSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/squad/': typeof SquadIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/pm/projects': typeof AdminPmProjectsRouteWithChildren
  '/admin/pm/services': typeof AdminPmServicesRouteWithChildren
  '/admin/system/currency': typeof AdminSystemCurrencyRoute
  '/admin/pm/': typeof AdminPmIndexRoute
  '/admin/pm/projects/$id': typeof AdminPmProjectsIdRoute
  '/admin/pm/services/new': typeof AdminPmServicesNewRoute
  '/admin/pm/services/$id/edit': typeof AdminPmServicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/affiliate/join': typeof AffiliateJoinRoute
  '/dashboard/my-products': typeof DashboardMyProductsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/handler/$': typeof HandlerSplatRoute
  '/squad/active': typeof SquadActiveRoute
  '/squad/missions': typeof SquadMissionsRoute
  '/squad/onboarding': typeof SquadOnboardingRoute
  '/squad/profile': typeof SquadProfileRoute
  '/view-design/$slug': typeof ViewDesignSlugRoute
  '/admin': typeof AdminIndexRoute
  '/affiliate': typeof AffiliateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/squad': typeof SquadIndexRoute
  '/support': typeof SupportIndexRoute
  '/admin/pm/projects': typeof AdminPmProjectsRouteWithChildren
  '/admin/pm/services': typeof AdminPmServicesRouteWithChildren
  '/admin/system/currency': typeof AdminSystemCurrencyRoute
  '/admin/pm': typeof AdminPmIndexRoute
  '/admin/pm/projects/$id': typeof AdminPmProjectsIdRoute
  '/admin/pm/services/new': typeof AdminPmServicesNewRoute
  '/admin/pm/services/$id/edit': typeof AdminPmServicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/squad': typeof SquadRouteWithChildren
  '/support': typeof SupportRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/affiliate/join': typeof AffiliateJoinRoute
  '/dashboard/my-products': typeof DashboardMyProductsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/handler/$': typeof HandlerSplatRoute
  '/squad/active': typeof SquadActiveRoute
  '/squad/missions': typeof SquadMissionsRoute
  '/squad/onboarding': typeof SquadOnboardingRoute
  '/squad/profile': typeof SquadProfileRoute
  '/view-design/$slug': typeof ViewDesignSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/squad/': typeof SquadIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/pm/projects': typeof AdminPmProjectsRouteWithChildren
  '/admin/pm/services': typeof AdminPmServicesRouteWithChildren
  '/admin/system/currency': typeof AdminSystemCurrencyRoute
  '/admin/pm/': typeof AdminPmIndexRoute
  '/admin/pm/projects/$id': typeof AdminPmProjectsIdRoute
  '/admin/pm/services/new': typeof AdminPmServicesNewRoute
  '/admin/pm/services/$id/edit': typeof AdminPmServicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/dashboard'
    | '/squad'
    | '/support'
    | '/admin/testimonials'
    | '/affiliate/join'
    | '/dashboard/my-products'
    | '/dashboard/support'
    | '/handler/$'
    | '/squad/active'
    | '/squad/missions'
    | '/squad/onboarding'
    | '/squad/profile'
    | '/view-design/$slug'
    | '/admin/'
    | '/affiliate/'
    | '/dashboard/'
    | '/squad/'
    | '/support/'
    | '/admin/pm/projects'
    | '/admin/pm/services'
    | '/admin/system/currency'
    | '/admin/pm/'
    | '/admin/pm/projects/$id'
    | '/admin/pm/services/new'
    | '/admin/pm/services/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/testimonials'
    | '/affiliate/join'
    | '/dashboard/my-products'
    | '/dashboard/support'
    | '/handler/$'
    | '/squad/active'
    | '/squad/missions'
    | '/squad/onboarding'
    | '/squad/profile'
    | '/view-design/$slug'
    | '/admin'
    | '/affiliate'
    | '/dashboard'
    | '/squad'
    | '/support'
    | '/admin/pm/projects'
    | '/admin/pm/services'
    | '/admin/system/currency'
    | '/admin/pm'
    | '/admin/pm/projects/$id'
    | '/admin/pm/services/new'
    | '/admin/pm/services/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate'
    | '/dashboard'
    | '/squad'
    | '/support'
    | '/admin/testimonials'
    | '/affiliate/join'
    | '/dashboard/my-products'
    | '/dashboard/support'
    | '/handler/$'
    | '/squad/active'
    | '/squad/missions'
    | '/squad/onboarding'
    | '/squad/profile'
    | '/view-design/$slug'
    | '/admin/'
    | '/affiliate/'
    | '/dashboard/'
    | '/squad/'
    | '/support/'
    | '/admin/pm/projects'
    | '/admin/pm/services'
    | '/admin/system/currency'
    | '/admin/pm/'
    | '/admin/pm/projects/$id'
    | '/admin/pm/services/new'
    | '/admin/pm/services/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  SquadRoute: typeof SquadRouteWithChildren
  SupportRoute: typeof SupportRouteWithChildren
  HandlerSplatRoute: typeof HandlerSplatRoute
  ViewDesignSlugRoute: typeof ViewDesignSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/squad/': {
      id: '/squad/'
      path: '/'
      fullPath: '/squad/'
      preLoaderRoute: typeof SquadIndexRouteImport
      parentRoute: typeof SquadRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/affiliate/': {
      id: '/affiliate/'
      path: '/'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AffiliateIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/view-design/$slug': {
      id: '/view-design/$slug'
      path: '/view-design/$slug'
      fullPath: '/view-design/$slug'
      preLoaderRoute: typeof ViewDesignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad/profile': {
      id: '/squad/profile'
      path: '/profile'
      fullPath: '/squad/profile'
      preLoaderRoute: typeof SquadProfileRouteImport
      parentRoute: typeof SquadRoute
    }
    '/squad/onboarding': {
      id: '/squad/onboarding'
      path: '/onboarding'
      fullPath: '/squad/onboarding'
      preLoaderRoute: typeof SquadOnboardingRouteImport
      parentRoute: typeof SquadRoute
    }
    '/squad/missions': {
      id: '/squad/missions'
      path: '/missions'
      fullPath: '/squad/missions'
      preLoaderRoute: typeof SquadMissionsRouteImport
      parentRoute: typeof SquadRoute
    }
    '/squad/active': {
      id: '/squad/active'
      path: '/active'
      fullPath: '/squad/active'
      preLoaderRoute: typeof SquadActiveRouteImport
      parentRoute: typeof SquadRoute
    }
    '/handler/$': {
      id: '/handler/$'
      path: '/handler/$'
      fullPath: '/handler/$'
      preLoaderRoute: typeof HandlerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-products': {
      id: '/dashboard/my-products'
      path: '/my-products'
      fullPath: '/dashboard/my-products'
      preLoaderRoute: typeof DashboardMyProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/affiliate/join': {
      id: '/affiliate/join'
      path: '/join'
      fullPath: '/affiliate/join'
      preLoaderRoute: typeof AffiliateJoinRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/': {
      id: '/admin/pm/'
      path: '/pm'
      fullPath: '/admin/pm/'
      preLoaderRoute: typeof AdminPmIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/currency': {
      id: '/admin/system/currency'
      path: '/system/currency'
      fullPath: '/admin/system/currency'
      preLoaderRoute: typeof AdminSystemCurrencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/services': {
      id: '/admin/pm/services'
      path: '/pm/services'
      fullPath: '/admin/pm/services'
      preLoaderRoute: typeof AdminPmServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/projects': {
      id: '/admin/pm/projects'
      path: '/pm/projects'
      fullPath: '/admin/pm/projects'
      preLoaderRoute: typeof AdminPmProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/services/new': {
      id: '/admin/pm/services/new'
      path: '/new'
      fullPath: '/admin/pm/services/new'
      preLoaderRoute: typeof AdminPmServicesNewRouteImport
      parentRoute: typeof AdminPmServicesRoute
    }
    '/admin/pm/projects/$id': {
      id: '/admin/pm/projects/$id'
      path: '/$id'
      fullPath: '/admin/pm/projects/$id'
      preLoaderRoute: typeof AdminPmProjectsIdRouteImport
      parentRoute: typeof AdminPmProjectsRoute
    }
    '/admin/pm/services/$id/edit': {
      id: '/admin/pm/services/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/pm/services/$id/edit'
      preLoaderRoute: typeof AdminPmServicesIdEditRouteImport
      parentRoute: typeof AdminPmServicesRoute
    }
  }
}

interface AdminPmProjectsRouteChildren {
  AdminPmProjectsIdRoute: typeof AdminPmProjectsIdRoute
}

const AdminPmProjectsRouteChildren: AdminPmProjectsRouteChildren = {
  AdminPmProjectsIdRoute: AdminPmProjectsIdRoute,
}

const AdminPmProjectsRouteWithChildren = AdminPmProjectsRoute._addFileChildren(
  AdminPmProjectsRouteChildren,
)

interface AdminPmServicesRouteChildren {
  AdminPmServicesNewRoute: typeof AdminPmServicesNewRoute
  AdminPmServicesIdEditRoute: typeof AdminPmServicesIdEditRoute
}

const AdminPmServicesRouteChildren: AdminPmServicesRouteChildren = {
  AdminPmServicesNewRoute: AdminPmServicesNewRoute,
  AdminPmServicesIdEditRoute: AdminPmServicesIdEditRoute,
}

const AdminPmServicesRouteWithChildren = AdminPmServicesRoute._addFileChildren(
  AdminPmServicesRouteChildren,
)

interface AdminRouteChildren {
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPmProjectsRoute: typeof AdminPmProjectsRouteWithChildren
  AdminPmServicesRoute: typeof AdminPmServicesRouteWithChildren
  AdminSystemCurrencyRoute: typeof AdminSystemCurrencyRoute
  AdminPmIndexRoute: typeof AdminPmIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPmProjectsRoute: AdminPmProjectsRouteWithChildren,
  AdminPmServicesRoute: AdminPmServicesRouteWithChildren,
  AdminSystemCurrencyRoute: AdminSystemCurrencyRoute,
  AdminPmIndexRoute: AdminPmIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AffiliateRouteChildren {
  AffiliateJoinRoute: typeof AffiliateJoinRoute
  AffiliateIndexRoute: typeof AffiliateIndexRoute
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliateJoinRoute: AffiliateJoinRoute,
  AffiliateIndexRoute: AffiliateIndexRoute,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

interface DashboardRouteChildren {
  DashboardMyProductsRoute: typeof DashboardMyProductsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMyProductsRoute: DashboardMyProductsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SquadRouteChildren {
  SquadActiveRoute: typeof SquadActiveRoute
  SquadMissionsRoute: typeof SquadMissionsRoute
  SquadOnboardingRoute: typeof SquadOnboardingRoute
  SquadProfileRoute: typeof SquadProfileRoute
  SquadIndexRoute: typeof SquadIndexRoute
}

const SquadRouteChildren: SquadRouteChildren = {
  SquadActiveRoute: SquadActiveRoute,
  SquadMissionsRoute: SquadMissionsRoute,
  SquadOnboardingRoute: SquadOnboardingRoute,
  SquadProfileRoute: SquadProfileRoute,
  SquadIndexRoute: SquadIndexRoute,
}

const SquadRouteWithChildren = SquadRoute._addFileChildren(SquadRouteChildren)

interface SupportRouteChildren {
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  SquadRoute: SquadRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
  HandlerSplatRoute: HandlerSplatRoute,
  ViewDesignSlugRoute: ViewDesignSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
