/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubmitTestimonialRouteImport } from './routes/submit-testimonial'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as PromosiRouteImport } from './routes/promosi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SquadIndexRouteImport } from './routes/squad.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PriceCalculatorIndexRouteImport } from './routes/price-calculator.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AffiliateIndexRouteImport } from './routes/affiliate.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ViewDesignSlugRouteImport } from './routes/view-design.$slug'
import { Route as SquadProfileRouteImport } from './routes/squad.profile'
import { Route as SquadOnboardingRouteImport } from './routes/squad.onboarding'
import { Route as SquadMissionsRouteImport } from './routes/squad.missions'
import { Route as SquadActiveRouteImport } from './routes/squad.active'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PriceCalculatorIdRouteImport } from './routes/price-calculator.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as HandlerSignInRouteImport } from './routes/handler/sign-in'
import { Route as HandlerSplatRouteImport } from './routes/handler/$'
import { Route as DigitalInvoicesIdRouteImport } from './routes/digital-invoices.$id'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard.quotes'
import { Route as DashboardMyProductsRouteImport } from './routes/dashboard.my-products'
import { Route as DashboardMissionsRouteImport } from './routes/dashboard.missions'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as ApiEstimatesRouteImport } from './routes/api.estimates'
import { Route as ApiDigitalCheckoutRouteImport } from './routes/api.digital-checkout'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as AffiliateResourcesRouteImport } from './routes/affiliate.resources'
import { Route as AffiliatePayoutsRouteImport } from './routes/affiliate.payouts'
import { Route as AffiliateJoinRouteImport } from './routes/affiliate.join'
import { Route as AffiliateDashboardRouteImport } from './routes/affiliate.dashboard'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLicensesRouteImport } from './routes/admin.licenses'
import { Route as AdminDigitalSalesRouteImport } from './routes/admin.digital-sales'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminPmIndexRouteImport } from './routes/admin.pm.index'
import { Route as AdminMarketingIndexRouteImport } from './routes/admin.marketing.index'
import { Route as SquadMissionsIdRouteImport } from './routes/squad.missions.$id'
import { Route as DashboardMissionsIdRouteImport } from './routes/dashboard.missions.$id'
import { Route as ApiSystemSeoRouteImport } from './routes/api.system.seo'
import { Route as ApiStoreOrderRouteImport } from './routes/api.store.order'
import { Route as ApiPaymentCreemRouteImport } from './routes/api.payment.creem'
import { Route as ApiMarketingSubscribeRouteImport } from './routes/api.marketing.subscribe'
import { Route as ApiCurrencyRatesRouteImport } from './routes/api.currency.rates'
import { Route as ApiBillingProofRouteImport } from './routes/api.billing.proof'
import { Route as AdminSystemWebhooksRouteImport } from './routes/admin.system.webhooks'
import { Route as AdminSystemStorageRouteImport } from './routes/admin.system.storage'
import { Route as AdminSystemSettingsRouteImport } from './routes/admin.system.settings'
import { Route as AdminSystemSeoRouteImport } from './routes/admin.system.seo'
import { Route as AdminSystemPricingRouteImport } from './routes/admin.system.pricing'
import { Route as AdminSystemPaymentRouteImport } from './routes/admin.system.payment'
import { Route as AdminSystemKeysRouteImport } from './routes/admin.system.keys'
import { Route as AdminSystemIntegrationsRouteImport } from './routes/admin.system.integrations'
import { Route as AdminSystemEmailRouteImport } from './routes/admin.system.email'
import { Route as AdminSystemCurrencyRouteImport } from './routes/admin.system.currency'
import { Route as AdminPmServicesRouteImport } from './routes/admin.pm.services'
import { Route as AdminPmProjectsRouteImport } from './routes/admin.pm.projects'
import { Route as AdminMarketingSubscribersRouteImport } from './routes/admin.marketing.subscribers'
import { Route as AdminMarketingPushRouteImport } from './routes/admin.marketing.push'
import { Route as AdminMarketingPromotionsRouteImport } from './routes/admin.marketing.promotions'
import { Route as AdminMarketingPopupsRouteImport } from './routes/admin.marketing.popups'
import { Route as AdminMarketingPayoutsRouteImport } from './routes/admin.marketing.payouts'
import { Route as AdminMarketingLeadsRouteImport } from './routes/admin.marketing.leads'
import { Route as AdminMarketingCouponsRouteImport } from './routes/admin.marketing.coupons'
import { Route as AdminMarketingBonusesRouteImport } from './routes/admin.marketing.bonuses'
import { Route as AdminMarketingAssetsRouteImport } from './routes/admin.marketing.assets'
import { Route as AdminMarketingAffiliatesRouteImport } from './routes/admin.marketing.affiliates'
import { Route as AdminFinanceSubscriptionsRouteImport } from './routes/admin.finance.subscriptions'
import { Route as AdminFinanceQuotesRouteImport } from './routes/admin.finance.quotes'
import { Route as AdminFinanceOrdersRouteImport } from './routes/admin.finance.orders'
import { Route as AdminFinanceDigitalOrdersRouteImport } from './routes/admin.finance.digital-orders'
import { Route as AdminPmServicesIndexRouteImport } from './routes/admin.pm.services.index'
import { Route as AdminPmProjectsIndexRouteImport } from './routes/admin.pm.projects.index'
import { Route as ApiSystemSeoPagesRouteImport } from './routes/api.system.seo.pages'
import { Route as ApiSystemKeysStatusRouteImport } from './routes/api.system.keys.status'
import { Route as ApiPaymentMidtransWebhookRouteImport } from './routes/api.payment.midtrans.webhook'
import { Route as ApiPaymentMidtransChargeRouteImport } from './routes/api.payment.midtrans.charge'
import { Route as ApiPaymentCreemWebhookRouteImport } from './routes/api.payment.creem.webhook'
import { Route as ApiIntegrationsVercelAuthorizeRouteImport } from './routes/api.integrations.vercel.authorize'
import { Route as ApiIntegrationsGithubCallbackRouteImport } from './routes/api.integrations.github.callback'
import { Route as ApiIntegrationsGithubAuthorizeRouteImport } from './routes/api.integrations.github.authorize'
import { Route as AdminSystemSeoPagesRouteImport } from './routes/admin.system.seo.pages'
import { Route as AdminPmServicesNewRouteImport } from './routes/admin.pm.services.new'
import { Route as AdminPmProjectsIdRouteImport } from './routes/admin.pm.projects.$id'
import { Route as ApiSystemSeoPagesIdRouteImport } from './routes/api.system.seo.pages.$id'
import { Route as ApiMarketingAffiliatePayoutRequestRouteImport } from './routes/api.marketing.affiliate.payout.request'
import { Route as AdminPmServicesIdEditRouteImport } from './routes/admin.pm.services.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitTestimonialRoute = SubmitTestimonialRouteImport.update({
  id: '/submit-testimonial',
  path: '/submit-testimonial',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosiRoute = PromosiRouteImport.update({
  id: '/promosi',
  path: '/promosi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const SquadIndexRoute = SquadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SquadRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceCalculatorIndexRoute = PriceCalculatorIndexRouteImport.update({
  id: '/price-calculator/',
  path: '/price-calculator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AffiliateIndexRoute = AffiliateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliateRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ViewDesignSlugRoute = ViewDesignSlugRouteImport.update({
  id: '/view-design/$slug',
  path: '/view-design/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadProfileRoute = SquadProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SquadRoute,
} as any)
const SquadOnboardingRoute = SquadOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SquadRoute,
} as any)
const SquadMissionsRoute = SquadMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => SquadRoute,
} as any)
const SquadActiveRoute = SquadActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => SquadRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceCalculatorIdRoute = PriceCalculatorIdRouteImport.update({
  id: '/price-calculator/$id',
  path: '/price-calculator/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HandlerSignInRoute = HandlerSignInRouteImport.update({
  id: '/handler/sign-in',
  path: '/handler/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HandlerSplatRoute = HandlerSplatRouteImport.update({
  id: '/handler/$',
  path: '/handler/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalInvoicesIdRoute = DigitalInvoicesIdRouteImport.update({
  id: '/digital-invoices/$id',
  path: '/digital-invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyProductsRoute = DashboardMyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMissionsRoute = DashboardMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstimatesRoute = ApiEstimatesRouteImport.update({
  id: '/api/estimates',
  path: '/api/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigitalCheckoutRoute = ApiDigitalCheckoutRouteImport.update({
  id: '/api/digital-checkout',
  path: '/api/digital-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateResourcesRoute = AffiliateResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AffiliateRoute,
} as any)
const AffiliatePayoutsRoute = AffiliatePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AffiliateRoute,
} as any)
const AffiliateJoinRoute = AffiliateJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AffiliateRoute,
} as any)
const AffiliateDashboardRoute = AffiliateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AffiliateRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDigitalSalesRoute = AdminDigitalSalesRouteImport.update({
  id: '/digital-sales',
  path: '/digital-sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmIndexRoute = AdminPmIndexRouteImport.update({
  id: '/pm/',
  path: '/pm/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingIndexRoute = AdminMarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => AdminRoute,
} as any)
const SquadMissionsIdRoute = SquadMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SquadMissionsRoute,
} as any)
const DashboardMissionsIdRoute = DashboardMissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardMissionsRoute,
} as any)
const ApiSystemSeoRoute = ApiSystemSeoRouteImport.update({
  id: '/api/system/seo',
  path: '/api/system/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreOrderRoute = ApiStoreOrderRouteImport.update({
  id: '/api/store/order',
  path: '/api/store/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreemRoute = ApiPaymentCreemRouteImport.update({
  id: '/api/payment/creem',
  path: '/api/payment/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingSubscribeRoute = ApiMarketingSubscribeRouteImport.update({
  id: '/api/marketing/subscribe',
  path: '/api/marketing/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrencyRatesRoute = ApiCurrencyRatesRouteImport.update({
  id: '/api/currency/rates',
  path: '/api/currency/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingProofRoute = ApiBillingProofRouteImport.update({
  id: '/api/billing/proof',
  path: '/api/billing/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemWebhooksRoute = AdminSystemWebhooksRouteImport.update({
  id: '/system/webhooks',
  path: '/system/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemStorageRoute = AdminSystemStorageRouteImport.update({
  id: '/system/storage',
  path: '/system/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemSettingsRoute = AdminSystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemSeoRoute = AdminSystemSeoRouteImport.update({
  id: '/system/seo',
  path: '/system/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemPricingRoute = AdminSystemPricingRouteImport.update({
  id: '/system/pricing',
  path: '/system/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemPaymentRoute = AdminSystemPaymentRouteImport.update({
  id: '/system/payment',
  path: '/system/payment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemKeysRoute = AdminSystemKeysRouteImport.update({
  id: '/system/keys',
  path: '/system/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemIntegrationsRoute = AdminSystemIntegrationsRouteImport.update({
  id: '/system/integrations',
  path: '/system/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemEmailRoute = AdminSystemEmailRouteImport.update({
  id: '/system/email',
  path: '/system/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemCurrencyRoute = AdminSystemCurrencyRouteImport.update({
  id: '/system/currency',
  path: '/system/currency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmServicesRoute = AdminPmServicesRouteImport.update({
  id: '/pm/services',
  path: '/pm/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmProjectsRoute = AdminPmProjectsRouteImport.update({
  id: '/pm/projects',
  path: '/pm/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingSubscribersRoute =
  AdminMarketingSubscribersRouteImport.update({
    id: '/marketing/subscribers',
    path: '/marketing/subscribers',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingPushRoute = AdminMarketingPushRouteImport.update({
  id: '/marketing/push',
  path: '/marketing/push',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingPromotionsRoute =
  AdminMarketingPromotionsRouteImport.update({
    id: '/marketing/promotions',
    path: '/marketing/promotions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingPopupsRoute = AdminMarketingPopupsRouteImport.update({
  id: '/marketing/popups',
  path: '/marketing/popups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingPayoutsRoute = AdminMarketingPayoutsRouteImport.update({
  id: '/marketing/payouts',
  path: '/marketing/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingLeadsRoute = AdminMarketingLeadsRouteImport.update({
  id: '/marketing/leads',
  path: '/marketing/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingCouponsRoute = AdminMarketingCouponsRouteImport.update({
  id: '/marketing/coupons',
  path: '/marketing/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingBonusesRoute = AdminMarketingBonusesRouteImport.update({
  id: '/marketing/bonuses',
  path: '/marketing/bonuses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingAssetsRoute = AdminMarketingAssetsRouteImport.update({
  id: '/marketing/assets',
  path: '/marketing/assets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingAffiliatesRoute =
  AdminMarketingAffiliatesRouteImport.update({
    id: '/marketing/affiliates',
    path: '/marketing/affiliates',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinanceSubscriptionsRoute =
  AdminFinanceSubscriptionsRouteImport.update({
    id: '/finance/subscriptions',
    path: '/finance/subscriptions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinanceQuotesRoute = AdminFinanceQuotesRouteImport.update({
  id: '/finance/quotes',
  path: '/finance/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceOrdersRoute = AdminFinanceOrdersRouteImport.update({
  id: '/finance/orders',
  path: '/finance/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceDigitalOrdersRoute =
  AdminFinanceDigitalOrdersRouteImport.update({
    id: '/finance/digital-orders',
    path: '/finance/digital-orders',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPmServicesIndexRoute = AdminPmServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPmServicesRoute,
} as any)
const AdminPmProjectsIndexRoute = AdminPmProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPmProjectsRoute,
} as any)
const ApiSystemSeoPagesRoute = ApiSystemSeoPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => ApiSystemSeoRoute,
} as any)
const ApiSystemKeysStatusRoute = ApiSystemKeysStatusRouteImport.update({
  id: '/api/system/keys/status',
  path: '/api/system/keys/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentMidtransWebhookRoute =
  ApiPaymentMidtransWebhookRouteImport.update({
    id: '/api/payment/midtrans/webhook',
    path: '/api/payment/midtrans/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentMidtransChargeRoute =
  ApiPaymentMidtransChargeRouteImport.update({
    id: '/api/payment/midtrans/charge',
    path: '/api/payment/midtrans/charge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentCreemWebhookRoute = ApiPaymentCreemWebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => ApiPaymentCreemRoute,
} as any)
const ApiIntegrationsVercelAuthorizeRoute =
  ApiIntegrationsVercelAuthorizeRouteImport.update({
    id: '/api/integrations/vercel/authorize',
    path: '/api/integrations/vercel/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubCallbackRoute =
  ApiIntegrationsGithubCallbackRouteImport.update({
    id: '/api/integrations/github/callback',
    path: '/api/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubAuthorizeRoute =
  ApiIntegrationsGithubAuthorizeRouteImport.update({
    id: '/api/integrations/github/authorize',
    path: '/api/integrations/github/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSystemSeoPagesRoute = AdminSystemSeoPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminSystemSeoRoute,
} as any)
const AdminPmServicesNewRoute = AdminPmServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPmServicesRoute,
} as any)
const AdminPmProjectsIdRoute = AdminPmProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPmProjectsRoute,
} as any)
const ApiSystemSeoPagesIdRoute = ApiSystemSeoPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSystemSeoPagesRoute,
} as any)
const ApiMarketingAffiliatePayoutRequestRoute =
  ApiMarketingAffiliatePayoutRequestRouteImport.update({
    id: '/api/marketing/affiliate/payout/request',
    path: '/api/marketing/affiliate/payout/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPmServicesIdEditRoute = AdminPmServicesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPmServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/experts': typeof ExpertsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/promosi': typeof PromosiRoute
  '/squad': typeof SquadRouteWithChildren
  '/submit-testimonial': typeof SubmitTestimonialRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/digital-sales': typeof AdminDigitalSalesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/join': typeof AffiliateJoinRoute
  '/affiliate/payouts': typeof AffiliatePayoutsRoute
  '/affiliate/resources': typeof AffiliateResourcesRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/digital-checkout': typeof ApiDigitalCheckoutRoute
  '/api/estimates': typeof ApiEstimatesRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/missions': typeof DashboardMissionsRouteWithChildren
  '/dashboard/my-products': typeof DashboardMyProductsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/digital-invoices/$id': typeof DigitalInvoicesIdRoute
  '/handler/$': typeof HandlerSplatRoute
  '/handler/sign-in': typeof HandlerSignInRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/price-calculator/$id': typeof PriceCalculatorIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/squad/active': typeof SquadActiveRoute
  '/squad/missions': typeof SquadMissionsRouteWithChildren
  '/squad/onboarding': typeof SquadOnboardingRoute
  '/squad/profile': typeof SquadProfileRoute
  '/view-design/$slug': typeof ViewDesignSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/price-calculator/': typeof PriceCalculatorIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/squad/': typeof SquadIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/finance/digital-orders': typeof AdminFinanceDigitalOrdersRoute
  '/admin/finance/orders': typeof AdminFinanceOrdersRoute
  '/admin/finance/quotes': typeof AdminFinanceQuotesRoute
  '/admin/finance/subscriptions': typeof AdminFinanceSubscriptionsRoute
  '/admin/marketing/affiliates': typeof AdminMarketingAffiliatesRoute
  '/admin/marketing/assets': typeof AdminMarketingAssetsRoute
  '/admin/marketing/bonuses': typeof AdminMarketingBonusesRoute
  '/admin/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/admin/marketing/leads': typeof AdminMarketingLeadsRoute
  '/admin/marketing/payouts': typeof AdminMarketingPayoutsRoute
  '/admin/marketing/popups': typeof AdminMarketingPopupsRoute
  '/admin/marketing/promotions': typeof AdminMarketingPromotionsRoute
  '/admin/marketing/push': typeof AdminMarketingPushRoute
  '/admin/marketing/subscribers': typeof AdminMarketingSubscribersRoute
  '/admin/pm/projects': typeof AdminPmProjectsRouteWithChildren
  '/admin/pm/services': typeof AdminPmServicesRouteWithChildren
  '/admin/system/currency': typeof AdminSystemCurrencyRoute
  '/admin/system/email': typeof AdminSystemEmailRoute
  '/admin/system/integrations': typeof AdminSystemIntegrationsRoute
  '/admin/system/keys': typeof AdminSystemKeysRoute
  '/admin/system/payment': typeof AdminSystemPaymentRoute
  '/admin/system/pricing': typeof AdminSystemPricingRoute
  '/admin/system/seo': typeof AdminSystemSeoRouteWithChildren
  '/admin/system/settings': typeof AdminSystemSettingsRoute
  '/admin/system/storage': typeof AdminSystemStorageRoute
  '/admin/system/webhooks': typeof AdminSystemWebhooksRoute
  '/api/billing/proof': typeof ApiBillingProofRoute
  '/api/currency/rates': typeof ApiCurrencyRatesRoute
  '/api/marketing/subscribe': typeof ApiMarketingSubscribeRoute
  '/api/payment/creem': typeof ApiPaymentCreemRouteWithChildren
  '/api/store/order': typeof ApiStoreOrderRoute
  '/api/system/seo': typeof ApiSystemSeoRouteWithChildren
  '/dashboard/missions/$id': typeof DashboardMissionsIdRoute
  '/squad/missions/$id': typeof SquadMissionsIdRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/pm/': typeof AdminPmIndexRoute
  '/admin/pm/projects/$id': typeof AdminPmProjectsIdRoute
  '/admin/pm/services/new': typeof AdminPmServicesNewRoute
  '/admin/system/seo/pages': typeof AdminSystemSeoPagesRoute
  '/api/integrations/github/authorize': typeof ApiIntegrationsGithubAuthorizeRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/vercel/authorize': typeof ApiIntegrationsVercelAuthorizeRoute
  '/api/payment/creem/webhook': typeof ApiPaymentCreemWebhookRoute
  '/api/payment/midtrans/charge': typeof ApiPaymentMidtransChargeRoute
  '/api/payment/midtrans/webhook': typeof ApiPaymentMidtransWebhookRoute
  '/api/system/keys/status': typeof ApiSystemKeysStatusRoute
  '/api/system/seo/pages': typeof ApiSystemSeoPagesRouteWithChildren
  '/admin/pm/projects/': typeof AdminPmProjectsIndexRoute
  '/admin/pm/services/': typeof AdminPmServicesIndexRoute
  '/admin/pm/services/$id/edit': typeof AdminPmServicesIdEditRoute
  '/api/marketing/affiliate/payout/request': typeof ApiMarketingAffiliatePayoutRequestRoute
  '/api/system/seo/pages/$id': typeof ApiSystemSeoPagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/experts': typeof ExpertsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/promosi': typeof PromosiRoute
  '/submit-testimonial': typeof SubmitTestimonialRoute
  '/terms': typeof TermsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/digital-sales': typeof AdminDigitalSalesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/join': typeof AffiliateJoinRoute
  '/affiliate/payouts': typeof AffiliatePayoutsRoute
  '/affiliate/resources': typeof AffiliateResourcesRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/digital-checkout': typeof ApiDigitalCheckoutRoute
  '/api/estimates': typeof ApiEstimatesRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/missions': typeof DashboardMissionsRouteWithChildren
  '/dashboard/my-products': typeof DashboardMyProductsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/digital-invoices/$id': typeof DigitalInvoicesIdRoute
  '/handler/$': typeof HandlerSplatRoute
  '/handler/sign-in': typeof HandlerSignInRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/price-calculator/$id': typeof PriceCalculatorIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/squad/active': typeof SquadActiveRoute
  '/squad/missions': typeof SquadMissionsRouteWithChildren
  '/squad/onboarding': typeof SquadOnboardingRoute
  '/squad/profile': typeof SquadProfileRoute
  '/view-design/$slug': typeof ViewDesignSlugRoute
  '/admin': typeof AdminIndexRoute
  '/affiliate': typeof AffiliateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/price-calculator': typeof PriceCalculatorIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/squad': typeof SquadIndexRoute
  '/support': typeof SupportIndexRoute
  '/admin/finance/digital-orders': typeof AdminFinanceDigitalOrdersRoute
  '/admin/finance/orders': typeof AdminFinanceOrdersRoute
  '/admin/finance/quotes': typeof AdminFinanceQuotesRoute
  '/admin/finance/subscriptions': typeof AdminFinanceSubscriptionsRoute
  '/admin/marketing/affiliates': typeof AdminMarketingAffiliatesRoute
  '/admin/marketing/assets': typeof AdminMarketingAssetsRoute
  '/admin/marketing/bonuses': typeof AdminMarketingBonusesRoute
  '/admin/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/admin/marketing/leads': typeof AdminMarketingLeadsRoute
  '/admin/marketing/payouts': typeof AdminMarketingPayoutsRoute
  '/admin/marketing/popups': typeof AdminMarketingPopupsRoute
  '/admin/marketing/promotions': typeof AdminMarketingPromotionsRoute
  '/admin/marketing/push': typeof AdminMarketingPushRoute
  '/admin/marketing/subscribers': typeof AdminMarketingSubscribersRoute
  '/admin/system/currency': typeof AdminSystemCurrencyRoute
  '/admin/system/email': typeof AdminSystemEmailRoute
  '/admin/system/integrations': typeof AdminSystemIntegrationsRoute
  '/admin/system/keys': typeof AdminSystemKeysRoute
  '/admin/system/payment': typeof AdminSystemPaymentRoute
  '/admin/system/pricing': typeof AdminSystemPricingRoute
  '/admin/system/seo': typeof AdminSystemSeoRouteWithChildren
  '/admin/system/settings': typeof AdminSystemSettingsRoute
  '/admin/system/storage': typeof AdminSystemStorageRoute
  '/admin/system/webhooks': typeof AdminSystemWebhooksRoute
  '/api/billing/proof': typeof ApiBillingProofRoute
  '/api/currency/rates': typeof ApiCurrencyRatesRoute
  '/api/marketing/subscribe': typeof ApiMarketingSubscribeRoute
  '/api/payment/creem': typeof ApiPaymentCreemRouteWithChildren
  '/api/store/order': typeof ApiStoreOrderRoute
  '/api/system/seo': typeof ApiSystemSeoRouteWithChildren
  '/dashboard/missions/$id': typeof DashboardMissionsIdRoute
  '/squad/missions/$id': typeof SquadMissionsIdRoute
  '/admin/marketing': typeof AdminMarketingIndexRoute
  '/admin/pm': typeof AdminPmIndexRoute
  '/admin/pm/projects/$id': typeof AdminPmProjectsIdRoute
  '/admin/pm/services/new': typeof AdminPmServicesNewRoute
  '/admin/system/seo/pages': typeof AdminSystemSeoPagesRoute
  '/api/integrations/github/authorize': typeof ApiIntegrationsGithubAuthorizeRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/vercel/authorize': typeof ApiIntegrationsVercelAuthorizeRoute
  '/api/payment/creem/webhook': typeof ApiPaymentCreemWebhookRoute
  '/api/payment/midtrans/charge': typeof ApiPaymentMidtransChargeRoute
  '/api/payment/midtrans/webhook': typeof ApiPaymentMidtransWebhookRoute
  '/api/system/keys/status': typeof ApiSystemKeysStatusRoute
  '/api/system/seo/pages': typeof ApiSystemSeoPagesRouteWithChildren
  '/admin/pm/projects': typeof AdminPmProjectsIndexRoute
  '/admin/pm/services': typeof AdminPmServicesIndexRoute
  '/admin/pm/services/$id/edit': typeof AdminPmServicesIdEditRoute
  '/api/marketing/affiliate/payout/request': typeof ApiMarketingAffiliatePayoutRequestRoute
  '/api/system/seo/pages/$id': typeof ApiSystemSeoPagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/experts': typeof ExpertsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/promosi': typeof PromosiRoute
  '/squad': typeof SquadRouteWithChildren
  '/submit-testimonial': typeof SubmitTestimonialRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/digital-sales': typeof AdminDigitalSalesRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/join': typeof AffiliateJoinRoute
  '/affiliate/payouts': typeof AffiliatePayoutsRoute
  '/affiliate/resources': typeof AffiliateResourcesRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/digital-checkout': typeof ApiDigitalCheckoutRoute
  '/api/estimates': typeof ApiEstimatesRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/missions': typeof DashboardMissionsRouteWithChildren
  '/dashboard/my-products': typeof DashboardMyProductsRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/digital-invoices/$id': typeof DigitalInvoicesIdRoute
  '/handler/$': typeof HandlerSplatRoute
  '/handler/sign-in': typeof HandlerSignInRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/price-calculator/$id': typeof PriceCalculatorIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/squad/active': typeof SquadActiveRoute
  '/squad/missions': typeof SquadMissionsRouteWithChildren
  '/squad/onboarding': typeof SquadOnboardingRoute
  '/squad/profile': typeof SquadProfileRoute
  '/view-design/$slug': typeof ViewDesignSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/affiliate/': typeof AffiliateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/price-calculator/': typeof PriceCalculatorIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/squad/': typeof SquadIndexRoute
  '/support/': typeof SupportIndexRoute
  '/admin/finance/digital-orders': typeof AdminFinanceDigitalOrdersRoute
  '/admin/finance/orders': typeof AdminFinanceOrdersRoute
  '/admin/finance/quotes': typeof AdminFinanceQuotesRoute
  '/admin/finance/subscriptions': typeof AdminFinanceSubscriptionsRoute
  '/admin/marketing/affiliates': typeof AdminMarketingAffiliatesRoute
  '/admin/marketing/assets': typeof AdminMarketingAssetsRoute
  '/admin/marketing/bonuses': typeof AdminMarketingBonusesRoute
  '/admin/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/admin/marketing/leads': typeof AdminMarketingLeadsRoute
  '/admin/marketing/payouts': typeof AdminMarketingPayoutsRoute
  '/admin/marketing/popups': typeof AdminMarketingPopupsRoute
  '/admin/marketing/promotions': typeof AdminMarketingPromotionsRoute
  '/admin/marketing/push': typeof AdminMarketingPushRoute
  '/admin/marketing/subscribers': typeof AdminMarketingSubscribersRoute
  '/admin/pm/projects': typeof AdminPmProjectsRouteWithChildren
  '/admin/pm/services': typeof AdminPmServicesRouteWithChildren
  '/admin/system/currency': typeof AdminSystemCurrencyRoute
  '/admin/system/email': typeof AdminSystemEmailRoute
  '/admin/system/integrations': typeof AdminSystemIntegrationsRoute
  '/admin/system/keys': typeof AdminSystemKeysRoute
  '/admin/system/payment': typeof AdminSystemPaymentRoute
  '/admin/system/pricing': typeof AdminSystemPricingRoute
  '/admin/system/seo': typeof AdminSystemSeoRouteWithChildren
  '/admin/system/settings': typeof AdminSystemSettingsRoute
  '/admin/system/storage': typeof AdminSystemStorageRoute
  '/admin/system/webhooks': typeof AdminSystemWebhooksRoute
  '/api/billing/proof': typeof ApiBillingProofRoute
  '/api/currency/rates': typeof ApiCurrencyRatesRoute
  '/api/marketing/subscribe': typeof ApiMarketingSubscribeRoute
  '/api/payment/creem': typeof ApiPaymentCreemRouteWithChildren
  '/api/store/order': typeof ApiStoreOrderRoute
  '/api/system/seo': typeof ApiSystemSeoRouteWithChildren
  '/dashboard/missions/$id': typeof DashboardMissionsIdRoute
  '/squad/missions/$id': typeof SquadMissionsIdRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/pm/': typeof AdminPmIndexRoute
  '/admin/pm/projects/$id': typeof AdminPmProjectsIdRoute
  '/admin/pm/services/new': typeof AdminPmServicesNewRoute
  '/admin/system/seo/pages': typeof AdminSystemSeoPagesRoute
  '/api/integrations/github/authorize': typeof ApiIntegrationsGithubAuthorizeRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/vercel/authorize': typeof ApiIntegrationsVercelAuthorizeRoute
  '/api/payment/creem/webhook': typeof ApiPaymentCreemWebhookRoute
  '/api/payment/midtrans/charge': typeof ApiPaymentMidtransChargeRoute
  '/api/payment/midtrans/webhook': typeof ApiPaymentMidtransWebhookRoute
  '/api/system/keys/status': typeof ApiSystemKeysStatusRoute
  '/api/system/seo/pages': typeof ApiSystemSeoPagesRouteWithChildren
  '/admin/pm/projects/': typeof AdminPmProjectsIndexRoute
  '/admin/pm/services/': typeof AdminPmServicesIndexRoute
  '/admin/pm/services/$id/edit': typeof AdminPmServicesIdEditRoute
  '/api/marketing/affiliate/payout/request': typeof ApiMarketingAffiliatePayoutRequestRoute
  '/api/system/seo/pages/$id': typeof ApiSystemSeoPagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/experts'
    | '/portfolio'
    | '/privacy'
    | '/promosi'
    | '/squad'
    | '/submit-testimonial'
    | '/support'
    | '/terms'
    | '/admin/clients'
    | '/admin/digital-sales'
    | '/admin/licenses'
    | '/admin/media'
    | '/admin/portfolio'
    | '/admin/products'
    | '/admin/support'
    | '/admin/team'
    | '/admin/testimonials'
    | '/affiliate/dashboard'
    | '/affiliate/join'
    | '/affiliate/payouts'
    | '/affiliate/resources'
    | '/api/checkout'
    | '/api/digital-checkout'
    | '/api/estimates'
    | '/checkout/$id'
    | '/dashboard/billing'
    | '/dashboard/inbox'
    | '/dashboard/missions'
    | '/dashboard/my-products'
    | '/dashboard/quotes'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/digital-invoices/$id'
    | '/handler/$'
    | '/handler/sign-in'
    | '/invoices/$id'
    | '/price-calculator/$id'
    | '/products/$slug'
    | '/services/$slug'
    | '/squad/active'
    | '/squad/missions'
    | '/squad/onboarding'
    | '/squad/profile'
    | '/view-design/$slug'
    | '/admin/'
    | '/affiliate/'
    | '/dashboard/'
    | '/price-calculator/'
    | '/products/'
    | '/services/'
    | '/squad/'
    | '/support/'
    | '/admin/finance/digital-orders'
    | '/admin/finance/orders'
    | '/admin/finance/quotes'
    | '/admin/finance/subscriptions'
    | '/admin/marketing/affiliates'
    | '/admin/marketing/assets'
    | '/admin/marketing/bonuses'
    | '/admin/marketing/coupons'
    | '/admin/marketing/leads'
    | '/admin/marketing/payouts'
    | '/admin/marketing/popups'
    | '/admin/marketing/promotions'
    | '/admin/marketing/push'
    | '/admin/marketing/subscribers'
    | '/admin/pm/projects'
    | '/admin/pm/services'
    | '/admin/system/currency'
    | '/admin/system/email'
    | '/admin/system/integrations'
    | '/admin/system/keys'
    | '/admin/system/payment'
    | '/admin/system/pricing'
    | '/admin/system/seo'
    | '/admin/system/settings'
    | '/admin/system/storage'
    | '/admin/system/webhooks'
    | '/api/billing/proof'
    | '/api/currency/rates'
    | '/api/marketing/subscribe'
    | '/api/payment/creem'
    | '/api/store/order'
    | '/api/system/seo'
    | '/dashboard/missions/$id'
    | '/squad/missions/$id'
    | '/admin/marketing/'
    | '/admin/pm/'
    | '/admin/pm/projects/$id'
    | '/admin/pm/services/new'
    | '/admin/system/seo/pages'
    | '/api/integrations/github/authorize'
    | '/api/integrations/github/callback'
    | '/api/integrations/vercel/authorize'
    | '/api/payment/creem/webhook'
    | '/api/payment/midtrans/charge'
    | '/api/payment/midtrans/webhook'
    | '/api/system/keys/status'
    | '/api/system/seo/pages'
    | '/admin/pm/projects/'
    | '/admin/pm/services/'
    | '/admin/pm/services/$id/edit'
    | '/api/marketing/affiliate/payout/request'
    | '/api/system/seo/pages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/docs'
    | '/experts'
    | '/portfolio'
    | '/privacy'
    | '/promosi'
    | '/submit-testimonial'
    | '/terms'
    | '/admin/clients'
    | '/admin/digital-sales'
    | '/admin/licenses'
    | '/admin/media'
    | '/admin/portfolio'
    | '/admin/products'
    | '/admin/support'
    | '/admin/team'
    | '/admin/testimonials'
    | '/affiliate/dashboard'
    | '/affiliate/join'
    | '/affiliate/payouts'
    | '/affiliate/resources'
    | '/api/checkout'
    | '/api/digital-checkout'
    | '/api/estimates'
    | '/checkout/$id'
    | '/dashboard/billing'
    | '/dashboard/inbox'
    | '/dashboard/missions'
    | '/dashboard/my-products'
    | '/dashboard/quotes'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/digital-invoices/$id'
    | '/handler/$'
    | '/handler/sign-in'
    | '/invoices/$id'
    | '/price-calculator/$id'
    | '/products/$slug'
    | '/services/$slug'
    | '/squad/active'
    | '/squad/missions'
    | '/squad/onboarding'
    | '/squad/profile'
    | '/view-design/$slug'
    | '/admin'
    | '/affiliate'
    | '/dashboard'
    | '/price-calculator'
    | '/products'
    | '/services'
    | '/squad'
    | '/support'
    | '/admin/finance/digital-orders'
    | '/admin/finance/orders'
    | '/admin/finance/quotes'
    | '/admin/finance/subscriptions'
    | '/admin/marketing/affiliates'
    | '/admin/marketing/assets'
    | '/admin/marketing/bonuses'
    | '/admin/marketing/coupons'
    | '/admin/marketing/leads'
    | '/admin/marketing/payouts'
    | '/admin/marketing/popups'
    | '/admin/marketing/promotions'
    | '/admin/marketing/push'
    | '/admin/marketing/subscribers'
    | '/admin/system/currency'
    | '/admin/system/email'
    | '/admin/system/integrations'
    | '/admin/system/keys'
    | '/admin/system/payment'
    | '/admin/system/pricing'
    | '/admin/system/seo'
    | '/admin/system/settings'
    | '/admin/system/storage'
    | '/admin/system/webhooks'
    | '/api/billing/proof'
    | '/api/currency/rates'
    | '/api/marketing/subscribe'
    | '/api/payment/creem'
    | '/api/store/order'
    | '/api/system/seo'
    | '/dashboard/missions/$id'
    | '/squad/missions/$id'
    | '/admin/marketing'
    | '/admin/pm'
    | '/admin/pm/projects/$id'
    | '/admin/pm/services/new'
    | '/admin/system/seo/pages'
    | '/api/integrations/github/authorize'
    | '/api/integrations/github/callback'
    | '/api/integrations/vercel/authorize'
    | '/api/payment/creem/webhook'
    | '/api/payment/midtrans/charge'
    | '/api/payment/midtrans/webhook'
    | '/api/system/keys/status'
    | '/api/system/seo/pages'
    | '/admin/pm/projects'
    | '/admin/pm/services'
    | '/admin/pm/services/$id/edit'
    | '/api/marketing/affiliate/payout/request'
    | '/api/system/seo/pages/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/experts'
    | '/portfolio'
    | '/privacy'
    | '/promosi'
    | '/squad'
    | '/submit-testimonial'
    | '/support'
    | '/terms'
    | '/admin/clients'
    | '/admin/digital-sales'
    | '/admin/licenses'
    | '/admin/media'
    | '/admin/portfolio'
    | '/admin/products'
    | '/admin/support'
    | '/admin/team'
    | '/admin/testimonials'
    | '/affiliate/dashboard'
    | '/affiliate/join'
    | '/affiliate/payouts'
    | '/affiliate/resources'
    | '/api/checkout'
    | '/api/digital-checkout'
    | '/api/estimates'
    | '/checkout/$id'
    | '/dashboard/billing'
    | '/dashboard/inbox'
    | '/dashboard/missions'
    | '/dashboard/my-products'
    | '/dashboard/quotes'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/digital-invoices/$id'
    | '/handler/$'
    | '/handler/sign-in'
    | '/invoices/$id'
    | '/price-calculator/$id'
    | '/products/$slug'
    | '/services/$slug'
    | '/squad/active'
    | '/squad/missions'
    | '/squad/onboarding'
    | '/squad/profile'
    | '/view-design/$slug'
    | '/admin/'
    | '/affiliate/'
    | '/dashboard/'
    | '/price-calculator/'
    | '/products/'
    | '/services/'
    | '/squad/'
    | '/support/'
    | '/admin/finance/digital-orders'
    | '/admin/finance/orders'
    | '/admin/finance/quotes'
    | '/admin/finance/subscriptions'
    | '/admin/marketing/affiliates'
    | '/admin/marketing/assets'
    | '/admin/marketing/bonuses'
    | '/admin/marketing/coupons'
    | '/admin/marketing/leads'
    | '/admin/marketing/payouts'
    | '/admin/marketing/popups'
    | '/admin/marketing/promotions'
    | '/admin/marketing/push'
    | '/admin/marketing/subscribers'
    | '/admin/pm/projects'
    | '/admin/pm/services'
    | '/admin/system/currency'
    | '/admin/system/email'
    | '/admin/system/integrations'
    | '/admin/system/keys'
    | '/admin/system/payment'
    | '/admin/system/pricing'
    | '/admin/system/seo'
    | '/admin/system/settings'
    | '/admin/system/storage'
    | '/admin/system/webhooks'
    | '/api/billing/proof'
    | '/api/currency/rates'
    | '/api/marketing/subscribe'
    | '/api/payment/creem'
    | '/api/store/order'
    | '/api/system/seo'
    | '/dashboard/missions/$id'
    | '/squad/missions/$id'
    | '/admin/marketing/'
    | '/admin/pm/'
    | '/admin/pm/projects/$id'
    | '/admin/pm/services/new'
    | '/admin/system/seo/pages'
    | '/api/integrations/github/authorize'
    | '/api/integrations/github/callback'
    | '/api/integrations/vercel/authorize'
    | '/api/payment/creem/webhook'
    | '/api/payment/midtrans/charge'
    | '/api/payment/midtrans/webhook'
    | '/api/system/keys/status'
    | '/api/system/seo/pages'
    | '/admin/pm/projects/'
    | '/admin/pm/services/'
    | '/admin/pm/services/$id/edit'
    | '/api/marketing/affiliate/payout/request'
    | '/api/system/seo/pages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  ExpertsRoute: typeof ExpertsRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  PromosiRoute: typeof PromosiRoute
  SquadRoute: typeof SquadRouteWithChildren
  SubmitTestimonialRoute: typeof SubmitTestimonialRoute
  SupportRoute: typeof SupportRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiDigitalCheckoutRoute: typeof ApiDigitalCheckoutRoute
  ApiEstimatesRoute: typeof ApiEstimatesRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  DigitalInvoicesIdRoute: typeof DigitalInvoicesIdRoute
  HandlerSplatRoute: typeof HandlerSplatRoute
  HandlerSignInRoute: typeof HandlerSignInRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  PriceCalculatorIdRoute: typeof PriceCalculatorIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ViewDesignSlugRoute: typeof ViewDesignSlugRoute
  PriceCalculatorIndexRoute: typeof PriceCalculatorIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiBillingProofRoute: typeof ApiBillingProofRoute
  ApiCurrencyRatesRoute: typeof ApiCurrencyRatesRoute
  ApiMarketingSubscribeRoute: typeof ApiMarketingSubscribeRoute
  ApiPaymentCreemRoute: typeof ApiPaymentCreemRouteWithChildren
  ApiStoreOrderRoute: typeof ApiStoreOrderRoute
  ApiSystemSeoRoute: typeof ApiSystemSeoRouteWithChildren
  ApiIntegrationsGithubAuthorizeRoute: typeof ApiIntegrationsGithubAuthorizeRoute
  ApiIntegrationsGithubCallbackRoute: typeof ApiIntegrationsGithubCallbackRoute
  ApiIntegrationsVercelAuthorizeRoute: typeof ApiIntegrationsVercelAuthorizeRoute
  ApiPaymentMidtransChargeRoute: typeof ApiPaymentMidtransChargeRoute
  ApiPaymentMidtransWebhookRoute: typeof ApiPaymentMidtransWebhookRoute
  ApiSystemKeysStatusRoute: typeof ApiSystemKeysStatusRoute
  ApiMarketingAffiliatePayoutRequestRoute: typeof ApiMarketingAffiliatePayoutRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-testimonial': {
      id: '/submit-testimonial'
      path: '/submit-testimonial'
      fullPath: '/submit-testimonial'
      preLoaderRoute: typeof SubmitTestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promosi': {
      id: '/promosi'
      path: '/promosi'
      fullPath: '/promosi'
      preLoaderRoute: typeof PromosiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/squad/': {
      id: '/squad/'
      path: '/'
      fullPath: '/squad/'
      preLoaderRoute: typeof SquadIndexRouteImport
      parentRoute: typeof SquadRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-calculator/': {
      id: '/price-calculator/'
      path: '/price-calculator'
      fullPath: '/price-calculator/'
      preLoaderRoute: typeof PriceCalculatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/affiliate/': {
      id: '/affiliate/'
      path: '/'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AffiliateIndexRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/view-design/$slug': {
      id: '/view-design/$slug'
      path: '/view-design/$slug'
      fullPath: '/view-design/$slug'
      preLoaderRoute: typeof ViewDesignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad/profile': {
      id: '/squad/profile'
      path: '/profile'
      fullPath: '/squad/profile'
      preLoaderRoute: typeof SquadProfileRouteImport
      parentRoute: typeof SquadRoute
    }
    '/squad/onboarding': {
      id: '/squad/onboarding'
      path: '/onboarding'
      fullPath: '/squad/onboarding'
      preLoaderRoute: typeof SquadOnboardingRouteImport
      parentRoute: typeof SquadRoute
    }
    '/squad/missions': {
      id: '/squad/missions'
      path: '/missions'
      fullPath: '/squad/missions'
      preLoaderRoute: typeof SquadMissionsRouteImport
      parentRoute: typeof SquadRoute
    }
    '/squad/active': {
      id: '/squad/active'
      path: '/active'
      fullPath: '/squad/active'
      preLoaderRoute: typeof SquadActiveRouteImport
      parentRoute: typeof SquadRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-calculator/$id': {
      id: '/price-calculator/$id'
      path: '/price-calculator/$id'
      fullPath: '/price-calculator/$id'
      preLoaderRoute: typeof PriceCalculatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handler/sign-in': {
      id: '/handler/sign-in'
      path: '/handler/sign-in'
      fullPath: '/handler/sign-in'
      preLoaderRoute: typeof HandlerSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handler/$': {
      id: '/handler/$'
      path: '/handler/$'
      fullPath: '/handler/$'
      preLoaderRoute: typeof HandlerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-invoices/$id': {
      id: '/digital-invoices/$id'
      path: '/digital-invoices/$id'
      fullPath: '/digital-invoices/$id'
      preLoaderRoute: typeof DigitalInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-products': {
      id: '/dashboard/my-products'
      path: '/my-products'
      fullPath: '/dashboard/my-products'
      preLoaderRoute: typeof DashboardMyProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/missions': {
      id: '/dashboard/missions'
      path: '/missions'
      fullPath: '/dashboard/missions'
      preLoaderRoute: typeof DashboardMissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/estimates': {
      id: '/api/estimates'
      path: '/api/estimates'
      fullPath: '/api/estimates'
      preLoaderRoute: typeof ApiEstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digital-checkout': {
      id: '/api/digital-checkout'
      path: '/api/digital-checkout'
      fullPath: '/api/digital-checkout'
      preLoaderRoute: typeof ApiDigitalCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/resources': {
      id: '/affiliate/resources'
      path: '/resources'
      fullPath: '/affiliate/resources'
      preLoaderRoute: typeof AffiliateResourcesRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/payouts': {
      id: '/affiliate/payouts'
      path: '/payouts'
      fullPath: '/affiliate/payouts'
      preLoaderRoute: typeof AffiliatePayoutsRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/join': {
      id: '/affiliate/join'
      path: '/join'
      fullPath: '/affiliate/join'
      preLoaderRoute: typeof AffiliateJoinRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/affiliate/dashboard': {
      id: '/affiliate/dashboard'
      path: '/dashboard'
      fullPath: '/affiliate/dashboard'
      preLoaderRoute: typeof AffiliateDashboardRouteImport
      parentRoute: typeof AffiliateRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/digital-sales': {
      id: '/admin/digital-sales'
      path: '/digital-sales'
      fullPath: '/admin/digital-sales'
      preLoaderRoute: typeof AdminDigitalSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/': {
      id: '/admin/pm/'
      path: '/pm'
      fullPath: '/admin/pm/'
      preLoaderRoute: typeof AdminPmIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/': {
      id: '/admin/marketing/'
      path: '/marketing'
      fullPath: '/admin/marketing/'
      preLoaderRoute: typeof AdminMarketingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/squad/missions/$id': {
      id: '/squad/missions/$id'
      path: '/$id'
      fullPath: '/squad/missions/$id'
      preLoaderRoute: typeof SquadMissionsIdRouteImport
      parentRoute: typeof SquadMissionsRoute
    }
    '/dashboard/missions/$id': {
      id: '/dashboard/missions/$id'
      path: '/$id'
      fullPath: '/dashboard/missions/$id'
      preLoaderRoute: typeof DashboardMissionsIdRouteImport
      parentRoute: typeof DashboardMissionsRoute
    }
    '/api/system/seo': {
      id: '/api/system/seo'
      path: '/api/system/seo'
      fullPath: '/api/system/seo'
      preLoaderRoute: typeof ApiSystemSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/order': {
      id: '/api/store/order'
      path: '/api/store/order'
      fullPath: '/api/store/order'
      preLoaderRoute: typeof ApiStoreOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/creem': {
      id: '/api/payment/creem'
      path: '/api/payment/creem'
      fullPath: '/api/payment/creem'
      preLoaderRoute: typeof ApiPaymentCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/subscribe': {
      id: '/api/marketing/subscribe'
      path: '/api/marketing/subscribe'
      fullPath: '/api/marketing/subscribe'
      preLoaderRoute: typeof ApiMarketingSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/currency/rates': {
      id: '/api/currency/rates'
      path: '/api/currency/rates'
      fullPath: '/api/currency/rates'
      preLoaderRoute: typeof ApiCurrencyRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/proof': {
      id: '/api/billing/proof'
      path: '/api/billing/proof'
      fullPath: '/api/billing/proof'
      preLoaderRoute: typeof ApiBillingProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/webhooks': {
      id: '/admin/system/webhooks'
      path: '/system/webhooks'
      fullPath: '/admin/system/webhooks'
      preLoaderRoute: typeof AdminSystemWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/storage': {
      id: '/admin/system/storage'
      path: '/system/storage'
      fullPath: '/admin/system/storage'
      preLoaderRoute: typeof AdminSystemStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/settings': {
      id: '/admin/system/settings'
      path: '/system/settings'
      fullPath: '/admin/system/settings'
      preLoaderRoute: typeof AdminSystemSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/seo': {
      id: '/admin/system/seo'
      path: '/system/seo'
      fullPath: '/admin/system/seo'
      preLoaderRoute: typeof AdminSystemSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/pricing': {
      id: '/admin/system/pricing'
      path: '/system/pricing'
      fullPath: '/admin/system/pricing'
      preLoaderRoute: typeof AdminSystemPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/payment': {
      id: '/admin/system/payment'
      path: '/system/payment'
      fullPath: '/admin/system/payment'
      preLoaderRoute: typeof AdminSystemPaymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/keys': {
      id: '/admin/system/keys'
      path: '/system/keys'
      fullPath: '/admin/system/keys'
      preLoaderRoute: typeof AdminSystemKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/integrations': {
      id: '/admin/system/integrations'
      path: '/system/integrations'
      fullPath: '/admin/system/integrations'
      preLoaderRoute: typeof AdminSystemIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/email': {
      id: '/admin/system/email'
      path: '/system/email'
      fullPath: '/admin/system/email'
      preLoaderRoute: typeof AdminSystemEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/currency': {
      id: '/admin/system/currency'
      path: '/system/currency'
      fullPath: '/admin/system/currency'
      preLoaderRoute: typeof AdminSystemCurrencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/services': {
      id: '/admin/pm/services'
      path: '/pm/services'
      fullPath: '/admin/pm/services'
      preLoaderRoute: typeof AdminPmServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/projects': {
      id: '/admin/pm/projects'
      path: '/pm/projects'
      fullPath: '/admin/pm/projects'
      preLoaderRoute: typeof AdminPmProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/subscribers': {
      id: '/admin/marketing/subscribers'
      path: '/marketing/subscribers'
      fullPath: '/admin/marketing/subscribers'
      preLoaderRoute: typeof AdminMarketingSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/push': {
      id: '/admin/marketing/push'
      path: '/marketing/push'
      fullPath: '/admin/marketing/push'
      preLoaderRoute: typeof AdminMarketingPushRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/promotions': {
      id: '/admin/marketing/promotions'
      path: '/marketing/promotions'
      fullPath: '/admin/marketing/promotions'
      preLoaderRoute: typeof AdminMarketingPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/popups': {
      id: '/admin/marketing/popups'
      path: '/marketing/popups'
      fullPath: '/admin/marketing/popups'
      preLoaderRoute: typeof AdminMarketingPopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/payouts': {
      id: '/admin/marketing/payouts'
      path: '/marketing/payouts'
      fullPath: '/admin/marketing/payouts'
      preLoaderRoute: typeof AdminMarketingPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/leads': {
      id: '/admin/marketing/leads'
      path: '/marketing/leads'
      fullPath: '/admin/marketing/leads'
      preLoaderRoute: typeof AdminMarketingLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/coupons': {
      id: '/admin/marketing/coupons'
      path: '/marketing/coupons'
      fullPath: '/admin/marketing/coupons'
      preLoaderRoute: typeof AdminMarketingCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/bonuses': {
      id: '/admin/marketing/bonuses'
      path: '/marketing/bonuses'
      fullPath: '/admin/marketing/bonuses'
      preLoaderRoute: typeof AdminMarketingBonusesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/assets': {
      id: '/admin/marketing/assets'
      path: '/marketing/assets'
      fullPath: '/admin/marketing/assets'
      preLoaderRoute: typeof AdminMarketingAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/affiliates': {
      id: '/admin/marketing/affiliates'
      path: '/marketing/affiliates'
      fullPath: '/admin/marketing/affiliates'
      preLoaderRoute: typeof AdminMarketingAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/subscriptions': {
      id: '/admin/finance/subscriptions'
      path: '/finance/subscriptions'
      fullPath: '/admin/finance/subscriptions'
      preLoaderRoute: typeof AdminFinanceSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/quotes': {
      id: '/admin/finance/quotes'
      path: '/finance/quotes'
      fullPath: '/admin/finance/quotes'
      preLoaderRoute: typeof AdminFinanceQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/orders': {
      id: '/admin/finance/orders'
      path: '/finance/orders'
      fullPath: '/admin/finance/orders'
      preLoaderRoute: typeof AdminFinanceOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/digital-orders': {
      id: '/admin/finance/digital-orders'
      path: '/finance/digital-orders'
      fullPath: '/admin/finance/digital-orders'
      preLoaderRoute: typeof AdminFinanceDigitalOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pm/services/': {
      id: '/admin/pm/services/'
      path: '/'
      fullPath: '/admin/pm/services/'
      preLoaderRoute: typeof AdminPmServicesIndexRouteImport
      parentRoute: typeof AdminPmServicesRoute
    }
    '/admin/pm/projects/': {
      id: '/admin/pm/projects/'
      path: '/'
      fullPath: '/admin/pm/projects/'
      preLoaderRoute: typeof AdminPmProjectsIndexRouteImport
      parentRoute: typeof AdminPmProjectsRoute
    }
    '/api/system/seo/pages': {
      id: '/api/system/seo/pages'
      path: '/pages'
      fullPath: '/api/system/seo/pages'
      preLoaderRoute: typeof ApiSystemSeoPagesRouteImport
      parentRoute: typeof ApiSystemSeoRoute
    }
    '/api/system/keys/status': {
      id: '/api/system/keys/status'
      path: '/api/system/keys/status'
      fullPath: '/api/system/keys/status'
      preLoaderRoute: typeof ApiSystemKeysStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/midtrans/webhook': {
      id: '/api/payment/midtrans/webhook'
      path: '/api/payment/midtrans/webhook'
      fullPath: '/api/payment/midtrans/webhook'
      preLoaderRoute: typeof ApiPaymentMidtransWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/midtrans/charge': {
      id: '/api/payment/midtrans/charge'
      path: '/api/payment/midtrans/charge'
      fullPath: '/api/payment/midtrans/charge'
      preLoaderRoute: typeof ApiPaymentMidtransChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/creem/webhook': {
      id: '/api/payment/creem/webhook'
      path: '/webhook'
      fullPath: '/api/payment/creem/webhook'
      preLoaderRoute: typeof ApiPaymentCreemWebhookRouteImport
      parentRoute: typeof ApiPaymentCreemRoute
    }
    '/api/integrations/vercel/authorize': {
      id: '/api/integrations/vercel/authorize'
      path: '/api/integrations/vercel/authorize'
      fullPath: '/api/integrations/vercel/authorize'
      preLoaderRoute: typeof ApiIntegrationsVercelAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/callback': {
      id: '/api/integrations/github/callback'
      path: '/api/integrations/github/callback'
      fullPath: '/api/integrations/github/callback'
      preLoaderRoute: typeof ApiIntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/authorize': {
      id: '/api/integrations/github/authorize'
      path: '/api/integrations/github/authorize'
      fullPath: '/api/integrations/github/authorize'
      preLoaderRoute: typeof ApiIntegrationsGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/seo/pages': {
      id: '/admin/system/seo/pages'
      path: '/pages'
      fullPath: '/admin/system/seo/pages'
      preLoaderRoute: typeof AdminSystemSeoPagesRouteImport
      parentRoute: typeof AdminSystemSeoRoute
    }
    '/admin/pm/services/new': {
      id: '/admin/pm/services/new'
      path: '/new'
      fullPath: '/admin/pm/services/new'
      preLoaderRoute: typeof AdminPmServicesNewRouteImport
      parentRoute: typeof AdminPmServicesRoute
    }
    '/admin/pm/projects/$id': {
      id: '/admin/pm/projects/$id'
      path: '/$id'
      fullPath: '/admin/pm/projects/$id'
      preLoaderRoute: typeof AdminPmProjectsIdRouteImport
      parentRoute: typeof AdminPmProjectsRoute
    }
    '/api/system/seo/pages/$id': {
      id: '/api/system/seo/pages/$id'
      path: '/$id'
      fullPath: '/api/system/seo/pages/$id'
      preLoaderRoute: typeof ApiSystemSeoPagesIdRouteImport
      parentRoute: typeof ApiSystemSeoPagesRoute
    }
    '/api/marketing/affiliate/payout/request': {
      id: '/api/marketing/affiliate/payout/request'
      path: '/api/marketing/affiliate/payout/request'
      fullPath: '/api/marketing/affiliate/payout/request'
      preLoaderRoute: typeof ApiMarketingAffiliatePayoutRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pm/services/$id/edit': {
      id: '/admin/pm/services/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/pm/services/$id/edit'
      preLoaderRoute: typeof AdminPmServicesIdEditRouteImport
      parentRoute: typeof AdminPmServicesRoute
    }
  }
}

interface AdminPmProjectsRouteChildren {
  AdminPmProjectsIdRoute: typeof AdminPmProjectsIdRoute
  AdminPmProjectsIndexRoute: typeof AdminPmProjectsIndexRoute
}

const AdminPmProjectsRouteChildren: AdminPmProjectsRouteChildren = {
  AdminPmProjectsIdRoute: AdminPmProjectsIdRoute,
  AdminPmProjectsIndexRoute: AdminPmProjectsIndexRoute,
}

const AdminPmProjectsRouteWithChildren = AdminPmProjectsRoute._addFileChildren(
  AdminPmProjectsRouteChildren,
)

interface AdminPmServicesRouteChildren {
  AdminPmServicesNewRoute: typeof AdminPmServicesNewRoute
  AdminPmServicesIndexRoute: typeof AdminPmServicesIndexRoute
  AdminPmServicesIdEditRoute: typeof AdminPmServicesIdEditRoute
}

const AdminPmServicesRouteChildren: AdminPmServicesRouteChildren = {
  AdminPmServicesNewRoute: AdminPmServicesNewRoute,
  AdminPmServicesIndexRoute: AdminPmServicesIndexRoute,
  AdminPmServicesIdEditRoute: AdminPmServicesIdEditRoute,
}

const AdminPmServicesRouteWithChildren = AdminPmServicesRoute._addFileChildren(
  AdminPmServicesRouteChildren,
)

interface AdminSystemSeoRouteChildren {
  AdminSystemSeoPagesRoute: typeof AdminSystemSeoPagesRoute
}

const AdminSystemSeoRouteChildren: AdminSystemSeoRouteChildren = {
  AdminSystemSeoPagesRoute: AdminSystemSeoPagesRoute,
}

const AdminSystemSeoRouteWithChildren = AdminSystemSeoRoute._addFileChildren(
  AdminSystemSeoRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDigitalSalesRoute: typeof AdminDigitalSalesRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFinanceDigitalOrdersRoute: typeof AdminFinanceDigitalOrdersRoute
  AdminFinanceOrdersRoute: typeof AdminFinanceOrdersRoute
  AdminFinanceQuotesRoute: typeof AdminFinanceQuotesRoute
  AdminFinanceSubscriptionsRoute: typeof AdminFinanceSubscriptionsRoute
  AdminMarketingAffiliatesRoute: typeof AdminMarketingAffiliatesRoute
  AdminMarketingAssetsRoute: typeof AdminMarketingAssetsRoute
  AdminMarketingBonusesRoute: typeof AdminMarketingBonusesRoute
  AdminMarketingCouponsRoute: typeof AdminMarketingCouponsRoute
  AdminMarketingLeadsRoute: typeof AdminMarketingLeadsRoute
  AdminMarketingPayoutsRoute: typeof AdminMarketingPayoutsRoute
  AdminMarketingPopupsRoute: typeof AdminMarketingPopupsRoute
  AdminMarketingPromotionsRoute: typeof AdminMarketingPromotionsRoute
  AdminMarketingPushRoute: typeof AdminMarketingPushRoute
  AdminMarketingSubscribersRoute: typeof AdminMarketingSubscribersRoute
  AdminPmProjectsRoute: typeof AdminPmProjectsRouteWithChildren
  AdminPmServicesRoute: typeof AdminPmServicesRouteWithChildren
  AdminSystemCurrencyRoute: typeof AdminSystemCurrencyRoute
  AdminSystemEmailRoute: typeof AdminSystemEmailRoute
  AdminSystemIntegrationsRoute: typeof AdminSystemIntegrationsRoute
  AdminSystemKeysRoute: typeof AdminSystemKeysRoute
  AdminSystemPaymentRoute: typeof AdminSystemPaymentRoute
  AdminSystemPricingRoute: typeof AdminSystemPricingRoute
  AdminSystemSeoRoute: typeof AdminSystemSeoRouteWithChildren
  AdminSystemSettingsRoute: typeof AdminSystemSettingsRoute
  AdminSystemStorageRoute: typeof AdminSystemStorageRoute
  AdminSystemWebhooksRoute: typeof AdminSystemWebhooksRoute
  AdminMarketingIndexRoute: typeof AdminMarketingIndexRoute
  AdminPmIndexRoute: typeof AdminPmIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminDigitalSalesRoute: AdminDigitalSalesRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFinanceDigitalOrdersRoute: AdminFinanceDigitalOrdersRoute,
  AdminFinanceOrdersRoute: AdminFinanceOrdersRoute,
  AdminFinanceQuotesRoute: AdminFinanceQuotesRoute,
  AdminFinanceSubscriptionsRoute: AdminFinanceSubscriptionsRoute,
  AdminMarketingAffiliatesRoute: AdminMarketingAffiliatesRoute,
  AdminMarketingAssetsRoute: AdminMarketingAssetsRoute,
  AdminMarketingBonusesRoute: AdminMarketingBonusesRoute,
  AdminMarketingCouponsRoute: AdminMarketingCouponsRoute,
  AdminMarketingLeadsRoute: AdminMarketingLeadsRoute,
  AdminMarketingPayoutsRoute: AdminMarketingPayoutsRoute,
  AdminMarketingPopupsRoute: AdminMarketingPopupsRoute,
  AdminMarketingPromotionsRoute: AdminMarketingPromotionsRoute,
  AdminMarketingPushRoute: AdminMarketingPushRoute,
  AdminMarketingSubscribersRoute: AdminMarketingSubscribersRoute,
  AdminPmProjectsRoute: AdminPmProjectsRouteWithChildren,
  AdminPmServicesRoute: AdminPmServicesRouteWithChildren,
  AdminSystemCurrencyRoute: AdminSystemCurrencyRoute,
  AdminSystemEmailRoute: AdminSystemEmailRoute,
  AdminSystemIntegrationsRoute: AdminSystemIntegrationsRoute,
  AdminSystemKeysRoute: AdminSystemKeysRoute,
  AdminSystemPaymentRoute: AdminSystemPaymentRoute,
  AdminSystemPricingRoute: AdminSystemPricingRoute,
  AdminSystemSeoRoute: AdminSystemSeoRouteWithChildren,
  AdminSystemSettingsRoute: AdminSystemSettingsRoute,
  AdminSystemStorageRoute: AdminSystemStorageRoute,
  AdminSystemWebhooksRoute: AdminSystemWebhooksRoute,
  AdminMarketingIndexRoute: AdminMarketingIndexRoute,
  AdminPmIndexRoute: AdminPmIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AffiliateRouteChildren {
  AffiliateDashboardRoute: typeof AffiliateDashboardRoute
  AffiliateJoinRoute: typeof AffiliateJoinRoute
  AffiliatePayoutsRoute: typeof AffiliatePayoutsRoute
  AffiliateResourcesRoute: typeof AffiliateResourcesRoute
  AffiliateIndexRoute: typeof AffiliateIndexRoute
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliateDashboardRoute: AffiliateDashboardRoute,
  AffiliateJoinRoute: AffiliateJoinRoute,
  AffiliatePayoutsRoute: AffiliatePayoutsRoute,
  AffiliateResourcesRoute: AffiliateResourcesRoute,
  AffiliateIndexRoute: AffiliateIndexRoute,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

interface DashboardMissionsRouteChildren {
  DashboardMissionsIdRoute: typeof DashboardMissionsIdRoute
}

const DashboardMissionsRouteChildren: DashboardMissionsRouteChildren = {
  DashboardMissionsIdRoute: DashboardMissionsIdRoute,
}

const DashboardMissionsRouteWithChildren =
  DashboardMissionsRoute._addFileChildren(DashboardMissionsRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardMissionsRoute: typeof DashboardMissionsRouteWithChildren
  DashboardMyProductsRoute: typeof DashboardMyProductsRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardMissionsRoute: DashboardMissionsRouteWithChildren,
  DashboardMyProductsRoute: DashboardMyProductsRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SquadMissionsRouteChildren {
  SquadMissionsIdRoute: typeof SquadMissionsIdRoute
}

const SquadMissionsRouteChildren: SquadMissionsRouteChildren = {
  SquadMissionsIdRoute: SquadMissionsIdRoute,
}

const SquadMissionsRouteWithChildren = SquadMissionsRoute._addFileChildren(
  SquadMissionsRouteChildren,
)

interface SquadRouteChildren {
  SquadActiveRoute: typeof SquadActiveRoute
  SquadMissionsRoute: typeof SquadMissionsRouteWithChildren
  SquadOnboardingRoute: typeof SquadOnboardingRoute
  SquadProfileRoute: typeof SquadProfileRoute
  SquadIndexRoute: typeof SquadIndexRoute
}

const SquadRouteChildren: SquadRouteChildren = {
  SquadActiveRoute: SquadActiveRoute,
  SquadMissionsRoute: SquadMissionsRouteWithChildren,
  SquadOnboardingRoute: SquadOnboardingRoute,
  SquadProfileRoute: SquadProfileRoute,
  SquadIndexRoute: SquadIndexRoute,
}

const SquadRouteWithChildren = SquadRoute._addFileChildren(SquadRouteChildren)

interface SupportRouteChildren {
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface ApiPaymentCreemRouteChildren {
  ApiPaymentCreemWebhookRoute: typeof ApiPaymentCreemWebhookRoute
}

const ApiPaymentCreemRouteChildren: ApiPaymentCreemRouteChildren = {
  ApiPaymentCreemWebhookRoute: ApiPaymentCreemWebhookRoute,
}

const ApiPaymentCreemRouteWithChildren = ApiPaymentCreemRoute._addFileChildren(
  ApiPaymentCreemRouteChildren,
)

interface ApiSystemSeoPagesRouteChildren {
  ApiSystemSeoPagesIdRoute: typeof ApiSystemSeoPagesIdRoute
}

const ApiSystemSeoPagesRouteChildren: ApiSystemSeoPagesRouteChildren = {
  ApiSystemSeoPagesIdRoute: ApiSystemSeoPagesIdRoute,
}

const ApiSystemSeoPagesRouteWithChildren =
  ApiSystemSeoPagesRoute._addFileChildren(ApiSystemSeoPagesRouteChildren)

interface ApiSystemSeoRouteChildren {
  ApiSystemSeoPagesRoute: typeof ApiSystemSeoPagesRouteWithChildren
}

const ApiSystemSeoRouteChildren: ApiSystemSeoRouteChildren = {
  ApiSystemSeoPagesRoute: ApiSystemSeoPagesRouteWithChildren,
}

const ApiSystemSeoRouteWithChildren = ApiSystemSeoRoute._addFileChildren(
  ApiSystemSeoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  ExpertsRoute: ExpertsRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  PromosiRoute: PromosiRoute,
  SquadRoute: SquadRouteWithChildren,
  SubmitTestimonialRoute: SubmitTestimonialRoute,
  SupportRoute: SupportRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiDigitalCheckoutRoute: ApiDigitalCheckoutRoute,
  ApiEstimatesRoute: ApiEstimatesRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  DigitalInvoicesIdRoute: DigitalInvoicesIdRoute,
  HandlerSplatRoute: HandlerSplatRoute,
  HandlerSignInRoute: HandlerSignInRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  PriceCalculatorIdRoute: PriceCalculatorIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ViewDesignSlugRoute: ViewDesignSlugRoute,
  PriceCalculatorIndexRoute: PriceCalculatorIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiBillingProofRoute: ApiBillingProofRoute,
  ApiCurrencyRatesRoute: ApiCurrencyRatesRoute,
  ApiMarketingSubscribeRoute: ApiMarketingSubscribeRoute,
  ApiPaymentCreemRoute: ApiPaymentCreemRouteWithChildren,
  ApiStoreOrderRoute: ApiStoreOrderRoute,
  ApiSystemSeoRoute: ApiSystemSeoRouteWithChildren,
  ApiIntegrationsGithubAuthorizeRoute: ApiIntegrationsGithubAuthorizeRoute,
  ApiIntegrationsGithubCallbackRoute: ApiIntegrationsGithubCallbackRoute,
  ApiIntegrationsVercelAuthorizeRoute: ApiIntegrationsVercelAuthorizeRoute,
  ApiPaymentMidtransChargeRoute: ApiPaymentMidtransChargeRoute,
  ApiPaymentMidtransWebhookRoute: ApiPaymentMidtransWebhookRoute,
  ApiSystemKeysStatusRoute: ApiSystemKeysStatusRoute,
  ApiMarketingAffiliatePayoutRequestRoute:
    ApiMarketingAffiliatePayoutRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
